name: ad_fairness
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - conda-forge::python=3.10
  - conda-forge::pip
  - conda-forge::flake8

  # - pytorch::pytorch-cuda=11.6
  # - pytorch::pytorch==1.13.1
  # - pytorch::torchvision==0.14.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision=0.15.0
  - conda-forge::torchmetrics
  - conda-forge::matplotlib
  - conda-forge::scikit-learn
  - conda-forge::pandas
  - conda-forge::nibabel
  - conda-forge::tqdm
  - conda-forge::kaggle
  - conda-forge::pydicom
  - conda-forge::h5py
  - conda-forge::einops
  - conda-forge::wandb

  - pip:
    - tensorboard

# variables:
#   RSNA_DIR: /vol/aimspace/users/meissen/datasets/RSNA
#   CAMCAN_DIR: /vol/aimspace/users/meissen/datasets/CamCAN
#   BRATS_DIR: /vol/aimspace/users/meissen/datasets/BraTS
#   MIMIC_CXR_DIR: /vol/aimspace/users/meissen/datasets/MIMIC-CXR
#   CXR14_DIR: /vol/aimspace/users/meissen/datasets/CXR8
