name: ad_fairness
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - flake8

  - pytorch
  - torchvision
  - torchmetrics
  - pytorch-cuda=11.6
  - matplotlib
  - scikit-learn
  - pandas
  - jupyter
  - tqdm
  - kaggle
  - pydicom
  - h5py
  - einops

  pip:
    - tensorboard
